run:
  modules-download-mode: readonly
  include-go-root: true

linters:
  # enable-all: true
  fast: false
  enable:
    - deadcode
    - errcheck
    - gosimple 
    - govet
    - ineffassign 
    - staticcheck 
    - structcheck
    - typecheck
    - unused
    - varcheck
    - errorlint
    - wsl
    - dogsled 
    - gofmt
    - goimports
    - lll
    - nestif
    - goconst
