# 调试模式：生产环境请关闭此项
debug: true
logger:
  level: debug
database:
  dsn: root:q32dmOcsGD@(mysql:3306)/rong?charset=utf8mb4&parseTime=True&loc=Local
server:
  http_port: 8080
jwt:
  secret: 9e8702b0106a8709ce062382095ab163
redis:
  uri: redis://redis-master:6379/1

#redis配置
#Redis服务器地址
  spring.redis.host=127.0.0.1
  #Redis服务器连接端口
  spring.redis.port=6379
  #Redis数据库索引（默认为0）
  spring.redis.database=0
  #连接池最大连接数（使用负值表示没有限制）
  spring.redis.jedis.pool.max-active=50
  #连接池最大阻塞等待时间（使用负值表示没有限制）
  spring.redis.jedis.pool.max-wait=3000
  #连接池中的最大空闲连接
  spring.redis.jedis.pool.max-idle=20
  #连接池中的最小空闲连接
  spring.redis.jedis.pool.min-idle=2
  #连接超时时间（毫秒）
  spring.redis.timeout=5000